export const ideas = [
"Go for a 20-minute walk and listen to a podcast",
"Clean your phone gallery and delete junk photos",
"Make a coffee and sit in silence for 10 minutes",
"Call someone you miss",
"Declutter one drawer in your house",
"Plan a weekend trip (even if you won’t go)",
"Watch a documentary on YouTube",
"Organize your desktop files",
"Read 10 pages of any book",
"Write 5 things you’re grateful for",
"Rearrange your room layout",
"Watch a stand-up comedy video",
"Try a 10-minute stretch routine",
"Make a playlist for your current mood",
"Research a country you want to visit",
"Clean your email inbox for 15 minutes",
"Take a power nap",
"Watch sunset or sunrise",
"Learn 5 new keyboard shortcuts",
"Cook something simple at home",
"Learn 5 words in a new language",
"Write down your 2026 goals",
"Check your bank expenses this month",
"Start a habit tracker",
"Watch a TED talk",
"Update your LinkedIn profile",
"Explore Google Earth random place",
"Take a long relaxing shower",
"Sort your wardrobe",
"Watch a classic movie",
"Try meditation for 10 minutes",
"Make a budget plan",
"Listen to a new music genre",
"Backup your phone photos",
"Research investing basics",
"Write a short journal entry",
"Make a to-do list for tomorrow",
"Stretch your neck and back",
"Watch travel vlogs",
"Read Wikipedia random article",
"Plan a dream home layout",
"Look at old photos and memories",
"Clean your workspace",
"Try breathing exercises",
"Write a future letter to yourself",
"Watch productivity videos",
"Try a home workout",
"Make a smoothie",
"Organize your bookmarks",
"Plan your next big purchase",
"Create a bucket list",
"Research a new hobby",
"Write a blog idea",
"Explore online courses",
"Plan your ideal daily routine",
"Try digital detox for 1 hour",
"Learn basic photography tips",
"Explore interior design ideas",
"Practice better posture",
"Make a life roadmap",
"Watch space videos",
"Learn basic chess tactics",
"Practice mindfulness",
"Explore freelancing ideas",
"Learn Canva basics",
"Create a reading list",
"Research healthy snacks",
"Try Pomodoro technique",
"Practice public speaking alone",
"Create a self-care routine",
"Explore startup ideas",
"Write business ideas",
"Plan fitness goals",
"Research passive income ideas",
"Learn sleep improvement tips",
"Make a weekly planner",
"Try journaling prompts",
"Watch nature videos",
"Explore minimal desk setups",
"Create a vision board",
"Write affirmations",
"Research productivity hacks",
"Explore design inspiration",
"Learn basic finance tips",
"Make a study playlist",
"Plan your dream vacation",
"Watch history videos",
"Research side hustle ideas",
"Clean your kitchen",
"Polish your shoes",
"Trim plants in your garden",
"Try new fruit or recipe",
"Organize pantry",
"Write a short story",
"Sketch something around you",
"Learn origami",
"Fold paper crane",
"Make a DIY craft",
"Decorate your room corner",
"Organize cables and electronics",
"Clean your glasses",
"Update passwords for safety",
"Check your insurance papers",
"Backup important documents",
"Clean your laptop keyboard",
"Wash your car or bike",
"Plan a new fitness challenge",
"Try stretching with music",
"Do yoga poses",
"Practice deep breathing",
"Write a motivational note",
"Plan gift ideas",
"Organize photos in albums",
"Delete unwanted apps",
"Check flight deals",
"Plan road trip route",
"Watch inspirational video",
"Practice typing speed",
"Learn a new skill online",
"Check trending news",
"Explore stock market basics",
"Do light home exercises",
"Write a gratitude letter to someone",
"Listen to an audiobook",
"Try new hairstyle ideas",
"Read a biography of a famous person",
"Organize your bookshelf",
"Try painting or doodling",
"Clean your fan blades",
"Vacuum floor and corners",
"Rearrange furniture",
"Make a vision or mood board",
"Try a new music instrument",
"Plan a picnic in nearby park",
"Write a daily reflection",
"Create a weekly to-do list",
"Practice meditation app",
"Try minimalism challenge",
"Research a random science fact",
"Plan indoor plant layout",
"Do a crossword puzzle",
"Play Sudoku",
"Write a poem",
"Learn basic coding snippet",
"Try learning a new language phrase",
"Explore motivational podcasts",
"Make a daily schedule",
"Check local events",
"Plan to visit museum",
"Try DIY home decor",
"Clean your balcony",
"Feed birds or pets",
"Watch classic animated movies",
"Listen to white noise",
"Create a relaxation corner",
"Write your own recipe",
"Try indoor photography",
"Make paper decorations",
"Watch historical documentaries",
"Organize your wardrobe by color",
"Plan a charity or donation",
"Write a short funny story",
"Clean your shoes",
"Check your medicine expiry dates",
"Plan a healthy snack menu",
"Try new tea or coffee variant",
"Make a mini garden indoors",
"Research life hacks",
"Do quick cardio exercises",
"Make a small calendar for future events",
"Organize wallet",
"Plan your monthly budget",
"Write a fun challenge list",
"Do mindful walking",
"Create a digital folder structure",
"Try origami animals",
"Read an article on psychology",
"Watch cooking tutorial",
"Plan photography ideas",
"Explore music playlists",
"Write your autobiography outline",
"Plan your next week outfits",
"Write a motivational message to yourself",
"Do breathing exercise in fresh air",
"Make a small indoor decoration",
"Organize your digital photos",
"Check upcoming movie releases",
"Try stretching exercises before sleep",
"Write a thank-you note",
"Sketch your dream house",
"Try a new hairstyle on yourself",
"Clean a neglected corner at home",
"Research your favorite sport history",
"Plan a friend meet-up",
"Write ideas for weekend activities",
"Organize stationery items",
"Check for discounts or deals online",
"Make a vision board for career",
"Read a motivational quote collection",
"Try a new board game",
"Research a famous personality",
"Make a playlist of your favorite songs",
"Do mindfulness meditation",
"Write a short essay on a topic",
"Create a simple budget planner",
"Try a digital detox challenge",
"Practice handwriting improvement",
"Explore online learning platforms",
"Make a mini scrapbook",
"Research eco-friendly habits",
"Try bodyweight exercises at home",
"Organize your kitchen shelf",
"Clean your fridge",
"Make fruit salad",
"Learn something new about tech",
"Write short-term goals",
"Plan a photography session",
"Do breathing exercises",
"Try a guided meditation",
"Make a home cleaning schedule",
"Check plants and water them",
"Research cultural facts",
"Watch travel documentaries",
"Try a new hobby craft",
"Plan a virtual meetup",
"Write a short story",
"Try journaling ideas",
"Plan weekend cooking",
"Create a playlist for workouts",
"Practice drawing",
"Clean your shoes and bags",
"Organize your books",
"Try reading a poetry collection",
"Research financial tips",
"Learn keyboard shortcuts",
"Try a DIY project",
"Organize your documents",
"Make a list of personal achievements",
"Plan a creative activity",
"Watch inspirational talks",
"Create your own mini vision board",
"Explore online tutorials",
"Try minimalism in one corner",
"Plan next month’s tasks",
"Make a gratitude journal",
"Check your subscription apps",
"Try learning new phrases",
"Explore online courses",
"Write a motivational paragraph",
"Organize your digital workspace",
"Try a new type of tea",
"Plan a mini celebration",
"Try indoor gardening",
"Clean and organize electronics",
"Research new productivity hacks",
"Write a short reflection",
"Plan a home workout schedule",
"Try new music genres",
"Check local weather and plan activities",
"Organize a small event",
"Try meditation techniques",
"Make a weekly goal tracker",
"Plan DIY decorations",
"Clean your car or bike",
"Make a creative plan for weekend",
"Try an indoor photography challenge",
"Make a list of books to read",
"Explore inspirational blogs",
"Try a short yoga session",
"Plan a nature walk",
"Write fun facts",
"Do a puzzle or brain teaser",
"Plan healthy meals",
"Try a new recipe",
"Organize wardrobe by season",
"Research environmental tips",
"Clean your study or workspace",
"Plan to meet an old friend",
"Try a random act of kindness",
"Organize your digital files",
"Write a list of achievements",
"Try creating your own short story",
"Watch an informative video",
"Plan a creative activity for family",
"Write daily reflections",
"Try a small painting activity",
"Plan a weekend cooking challenge",
"Check online tutorials for hobbies",
"Make a small travel plan",
"Research interesting facts",
"Write motivational notes for yourself",
"Plan indoor exercises",
"Try digital organization",
"Organize small items at home",
"Clean a neglected corner",
"Make a mini garden plan",
"Try a guided breathing exercise",
"Plan creative indoor activities",
"Write ideas for next week",
"Try a mindfulness exercise",
"Plan home decorations",
"Organize your personal items",
"Write reflections on past week",
"Research a topic of interest",
"Make a plan for weekend fun",
"Try a short creative project",
"Plan healthy snack ideas",
"Check your finances",
"Try a creative drawing",
"Plan a mini photography project",
"Write your thoughts in journal",
"Try new music playlist",
"Organize your room corners",
"Plan your learning schedule",
"Try a short meditation session",
"Write motivational affirmations",
"Organize your digital photos",
"Plan a hobby session",
"Try a DIY decoration",
"Research new life hacks",
"Try a short workout session",
"Write ideas for future goals",
"Plan a fun activity",
"Check upcoming events",
"Make a weekend checklist",
"Try creative writing",
"Organize your book collection",
"Plan home cleaning tasks",
"Write a reflection on achievements",
"Try a simple craft",
"Plan a fun outdoor activity",
"Check learning resources",
"Try a short yoga session",
"Plan weekend relaxation",
"Write notes about your hobbies",
"Organize your wardrobe",
"Plan mini projects at home",
"Try a photography exercise",
"Make a creative plan",
"Write a daily gratitude note",
"Plan indoor entertainment",
"Try a new snack recipe",
"Organize personal documents",
"Plan outdoor walk",
"Write a short motivational text",
"Try a mindfulness exercise",
"Plan a small art project",
"Organize your digital files",
"Write ideas for a blog",
"Try a new hobby",
"Plan a home improvement task",
"Try a short meditation",
"Write a short story or poem",
"Organize your workspace",
"Plan a self-care activity",
"Try a creative DIY project",
"Make a weekend plan",
"Write a reflection",
"Plan indoor exercise",
"Try new recipes",
"Organize your study area",
"Plan creative activities",
"Try fun indoor games",
"Write ideas for personal growth",
"Plan a mini cleaning challenge",
"Try creative photography",
"Organize your kitchen",
"Plan a small garden project",
"Write motivational notes",
"Try simple workouts",
"Plan weekend relaxation activities",
"Organize your digital workspace",
"Write reflections and ideas",
"Plan mini home improvements",
"Try art and craft activities",
"Organize your bookshelf",
"Plan a photography challenge",
"Write gratitude notes",
"Try short meditation sessions",
"Plan indoor hobbies",
"Organize your wardrobe and closet",
"Write ideas for fun projects",
"Plan home DIY projects",
"Try small fitness challenges",
"Organize your personal space",
"Plan weekend leisure activities",
"Write reflections in journal",
"Try new indoor creative activities",
"Organize files and documents",
"Plan small cooking projects",
"Write motivational quotes",
"Try short breathing exercises",
"Plan indoor learning sessions",
"Organize your desktop and digital files",
"Write notes about personal growth",
"Plan self-care and wellness activities",
"Try creative writing exercises",
"Organize your personal library",
"Plan small fun activities",
"Write reflections on life",
"Try short mindfulness exercises",
"Plan indoor fitness routines",
"Organize digital photos and media",
"Write ideas for creative projects",
"Plan fun DIY activities",
"Try art or sketching projects",
"Organize your personal notes",
"Plan a weekend relaxation routine",
"Write motivational affirmations",
"Try short physical exercises",
"Plan indoor hobby activities",
"Organize your home corners",
"Write notes for personal improvement",
"Plan small gardening projects",
"Try creative short writing",
"Organize personal collections",
"Plan a productive day at home",
"Write reflections on achievements",
"Try simple craft activities",
"Plan indoor leisure activities",
"Organize your wardrobe neatly",
"Write ideas for future plans",
"Plan short fitness challenges",
"Try mindfulness or meditation",
"Organize your desk and study area",
"Write motivational journals",
"Plan a small DIY home project",
"Try indoor creative exercises",
"Organize kitchen shelves and pantry",
"Write reflections and thoughts",
"Plan a mini home decorating project",
"Try art or DIY craft",
"Organize your files and documents",
"Write ideas for weekend fun",
"Plan creative indoor projects",
"Try a short relaxation session",
"Organize your home workspace",
"Write motivational thoughts",
"Plan short indoor learning tasks",
"Try short creative exercises",
"Organize your digital notes",
"Write ideas for hobbies",
"Plan indoor wellness activities",
"Try small DIY home projects",
"Organize your bookshelf and books",
"Write reflections for personal growth",
"Plan indoor creative challenges",
"Try short meditation exercises",
"Organize your personal files",
"Write ideas for self-care",
"Plan a fun indoor activity",
"Try short artistic projects",
"Organize your wardrobe and accessories",
"Write motivational notes for yourself",
"Plan mini home improvement tasks",
"Try small creative writing",
"Organize your room corners",
"Write reflections on your week",
"Plan small indoor fitness sessions",
"Try a short breathing technique",
"Organize your study desk",
"Write ideas for personal hobbies",
"Plan indoor relaxation routine",
"Try creative sketching",
"Organize your home neatly",
"Write motivational journals",
"Plan a short creative session",
"Try DIY craft activities",
"Organize your kitchen and pantry",
"Write reflections on life",
"Plan small indoor projects",
"Try a quick home workout",
"Organize your digital media",
"Write ideas for personal growth",
"Plan indoor entertainment ideas",
"Try short mindfulness exercises",
"Organize your wardrobe and closet",
"Write motivational thoughts",
"Plan fun and creative indoor activities",
"Try small DIY projects",
"Organize your personal collections",
"Write reflections and ideas",
"Plan a weekend creative routine",
"Try short meditation sessions",
"Organize your desk and workspace",
"Write motivational affirmations",
"Plan indoor learning challenges",
"Try creative artistic exercises",
"Organize your room corners",
"Write ideas for self-care",
"Plan indoor hobby projects",
"Try small home improvement projects",
"Organize kitchen shelves",
"Write reflections on achievements",
"Plan indoor wellness activities",
"Try a short creative writing session",
"Organize digital notes",
"Write motivational journals",
"Plan small indoor fitness routines",
"Try DIY home decorating ideas",
"Organize your books and bookshelf",
"Write ideas for personal growth",
"Plan indoor artistic activities",
"Try short mindfulness sessions",
"Organize your wardrobe neatly",
"Write motivational thoughts",
"Plan mini home creative projects",
"Try short relaxation exercises",
"Organize your personal files",
"Write reflections and ideas",
"Plan a fun indoor weekend",
"Try creative sketching and drawing",
"Organize your study area",
"Write motivational notes",
"Plan short indoor learning tasks",
"Try small DIY crafts",
"Organize your digital workspace",
"Write ideas for personal hobbies",
"Plan indoor fitness and wellness activities",
"Try short creative writing exercises",
"Organize your room corners",
"Write reflections on your week",
"Plan mini home improvement activities",
"Try a quick mindfulness session",
"Organize your books and media",
"Write motivational affirmations",
"Plan short indoor creative projects",
"Try DIY home organization",
"Organize kitchen and pantry",
"Write ideas for weekend fun",
"Plan indoor artistic sessions",
"Try short breathing exercises",
"Organize your personal space",
"Write reflections and ideas",
"Plan indoor learning activities",
"Try small home fitness exercises",
"Organize your wardrobe and closet",
"Write motivational thoughts",
"Plan mini indoor DIY projects",
"Try creative sketching or painting",
"Organize your desk and workspace",
"Write ideas for self-care",
"Plan indoor hobby challenges",
"Try short meditation or mindfulness",
"Organize your digital files",
"Write reflections for personal growth",
"Plan a creative indoor routine",
"Try small DIY home projects",
"Organize your room corners",
"Write motivational journals",
"Plan indoor fitness challenges",
"Try creative short writing",
"Organize kitchen shelves",
"Write ideas for personal development",
"Plan small indoor artistic projects",
"Try a short home workout",
"Organize your books and collection",
"Write reflections and thoughts",
"Plan indoor creative sessions",
"Try short mindfulness techniques",
"Organize your wardrobe neatly",
"Write motivational affirmations",
"Plan mini DIY home tasks",
"Try short creative exercises",
"Organize your study desk",
"Write ideas for hobbies and growth",
"Plan indoor wellness activities",
"Try a quick meditation session",
"Organize your personal files",
"Write reflections and ideas",
"Plan small home improvement projects",
"Try DIY craft activities",
"Organize your room corners",
"Write motivational notes",
"Plan indoor learning sessions",
"Try short relaxation exercises",
"Organize your digital workspace",
"Write ideas for personal growth",
"Plan indoor creative projects",
"Try small home artistic activities",
"Organize your kitchen and pantry",
"Write reflections and ideas",
"Plan mini weekend fun activities",
"Try creative sketching or painting",
"Organize your wardrobe and closet",
"Write motivational journals",
"Plan indoor hobby challenges",
"Try a quick home fitness session",
"Organize your study desk",
"Write ideas for personal hobbies",
"Plan indoor mindfulness sessions",
"Try short creative writing exercises",
"Organize books and media collection",
"Write reflections and motivational notes",
"Plan mini indoor DIY projects",
"Try short relaxation techniques",
"Organize your personal space",
"Write ideas for personal growth",
"Plan indoor learning and creative sessions",
"Try small home improvement tasks",
"Organize your desk and workspace",
"Write motivational journals",
"Plan indoor artistic activities",
"Try short mindfulness exercises",
"Organize wardrobe and shelves",
"Write reflections and ideas",
"Plan mini weekend creative projects"
]
